#!/usr/bin/env python3
# ========================================================
# ZIL FRAMEWORK: MACH-O CDHASH EXTRACTOR (PROPER XNU PARSER)
# ========================================================
import os
import struct
import hashlib
import sys

# Konfigurasi Path
TOOLS_BIN_DIR = "tools/bin/"
OUTPUT_RUST_FILE = "core/executor/src/trusted_hashes.rs"

# Konstanta Mach-O & Code Signature
MH_MAGIC_64 = 0xfeedfacf
LC_CODE_SIGNATURE = 0x1d
CSMAGIC_EMBEDDED_SIGNATURE = 0xfade0cc0  # SuperBlob
CSMAGIC_CODEDIRECTORY = 0xfade0c02       # CodeDirectory

def extract_cdhash_from_macho(filepath):
    """
    Membedah Mach-O 64-bit untuk mengekstrak CDHash murni
    dari Code Directory Blob.
    """
    with open(filepath, "rb") as f:
        # 1. Validasi Mach-O 64-bit Header (Little-Endian)
        magic = struct.unpack('<I', f.read(4))[0]
        if magic != MH_MAGIC_64:
            print(f"[-] BUKAN MACH-O 64-BIT: {filepath}")
            return None
        
        # Lewati cputype, cpusubtype, filetype (12 bytes)
        f.seek(12, 1) 
        ncmds, sizeofcmds = struct.unpack('<II', f.read(8))
        
        # Lewati sisa header mach_header_64 (flags, reserved)
        f.seek(8, 1) 
        
        # 2. Cari Load Command: LC_CODE_SIGNATURE
        sig_offset = 0
        for _ in range(ncmds):
            cmd, cmdsize = struct.unpack('<II', f.read(8))
            if cmd == LC_CODE_SIGNATURE:
                sig_offset, _ = struct.unpack('<II', f.read(8))
                break
            # Lompat ke command berikutnya
            f.seek(cmdsize - 8, 1) 
            
        if sig_offset == 0:
            print(f"[-] TIDAK ADA SIGNATURE (Jalankan ldid dulu!): {filepath}")
            return None
            
        # 3. Masuk ke Zona Code Signature (PERINGATAN: Berubah jadi BIG-ENDIAN)
        f.seek(sig_offset)
        smagic, slength, count = struct.unpack('>III', f.read(12))
        
        if smagic != CSMAGIC_EMBEDDED_SIGNATURE:
            print(f"[-] SUPERBLOB RUSAK: {filepath}")
            return None
            
        # 4. Cari Code Directory di dalam SuperBlob
        for _ in range(count):
            blob_type, blob_offset = struct.unpack('>II', f.read(8))
            if blob_type == 0: # 0 adalah index untuk CodeDirectory
                
                # Lompat ke awal Code Directory
                f.seek(sig_offset + blob_offset)
                cmagic, clength = struct.unpack('>II', f.read(8))
                
                if cmagic == CSMAGIC_CODEDIRECTORY:
                    # Kembali ke awal Code Directory blob untuk membaca seluruhnya
                    f.seek(sig_offset + blob_offset)
                    cd_data = f.read(clength)
                    
                    # 5. Eksekusi Kriptografi Apple: SHA-256 dipotong 20 Byte
                    full_hash = hashlib.sha256(cd_data).digest()
                    cdhash = full_hash[:20]
                    return cdhash
                    
        print(f"[-] CODE DIRECTORY TIDAK DITEMUKAN: {filepath}")
        return None

def generate_rust_module(hashes, output_path):
    with open(output_path, "w") as f:
        f.write("//! AUTO-GENERATED BY build_cdhash_list.py\n")
        f.write("//! MACH-O PARSER MODE: ACTIVE\n\n")
        f.write("#![no_std]\n\n")
        f.write(f"pub const TRUSTED_BINARIES_COUNT: usize = {len(hashes)};\n\n")
        
        f.write("pub const TRUSTED_CDHASHES: [[u8; 20]; TRUSTED_BINARIES_COUNT] = [\n")
        
        for name, cdhash in hashes:
            hex_array = ", ".join([f"0x{b:02x}" for b in cdhash])
            f.write(f"    // Biner: {name}\n")
            f.write(f"    [{hex_array}],\n")
            
        f.write("];\n")

def main():
    print("[*] Membedah Mach-O & Mengekstrak CDHash...")
    
    if not os.path.exists(TOOLS_BIN_DIR):
        print(f"[!] Direktori {TOOLS_BIN_DIR} tidak ditemukan.")
        sys.exit(1)

    hashes = []
    for filename in os.listdir(TOOLS_BIN_DIR):
        filepath = os.path.join(TOOLS_BIN_DIR, filename)
        if os.path.isfile(filepath):
            cdhash = extract_cdhash_from_macho(filepath)
            if cdhash:
                hashes.append((filename, cdhash))
                print(f"    -> [VALID] {filename} (CDHash: {cdhash.hex()})")

    generate_rust_module(hashes, OUTPUT_RUST_FILE)
    print(f"[*] Selesai. Injeksi TrustCache siap dikompilasi ke Biner B.")

if __name__ == "__main__":
    main()